INSERT OR REPLACE INTO companions (id,name,native_name,gender,nationality,age,languages_json,rating,review_count,price,eta,hospitals_json,experience,active) VALUES
('c01','Wang Fang','王芳','female','China',32,'["zh-CN","ko","en"]',5.0,210,18000,16,'["Seoul National University Hospital","Korea University Anam Hospital"]','熟悉首尔大学医院和高丽大学安岩医院的挂号、检查、缴费与药房流程。',1),
('c02','Kim Somin','김소민','female','Korea',29,'["ko","zh-CN","en"]',4.9,188,15000,20,'["Severance Hospital","Seoul St. Marys Hospital"]','国际诊疗中心志愿服务三年，熟悉门诊、急诊和保险结算。',1),
('c03','Lee Jiwon','이지원','male','Korea',35,'["ko","zh-CN","ja"]',4.8,146,13000,24,'["Asan Medical Center","Samsung Medical Center"]','熟悉影像检查和专科转诊流程。',1),
('c04','Minh Anh','Minh Anh','female','Vietnam',27,'["vi","ko","en"]',4.9,132,14000,18,'["Seoul Medical Center","Konkuk University Hospital"]','越南语医疗口译员，熟悉女性健康、儿科和内科流程。',1),
('c05','Sato Haruki','佐藤春樹','male','Japan',41,'["ja","ko","en"]',4.7,98,16000,35,'["Severance Hospital","Soonchunhyang University Hospital"]','日语医疗沟通和高龄患者陪诊经验丰富。',1),
('c06','Ananda Priya','अनंदा प्रिया','female','India',31,'["hi","en","ko"]',4.8,121,17000,28,'["Samsung Medical Center","Asan Medical Center"]','英语、印地语双语陪诊，熟悉国际诊疗预约与检查准备。',1),
('c07','Nur Aisyah','Nur Aisyah','female','Malaysia',34,'["ms","en","ko","id"]',4.9,156,15500,22,'["Seoul National University Hospital","Seoul St. Marys Hospital"]','熟悉清真饮食、宗教需求沟通和住院陪护流程。',1),
('c08','Ahmed Hassan','أحمد حسن','male','Egypt',38,'["ar","en","ko"]',4.8,115,16500,30,'["Asan Medical Center","Samsung Medical Center"]','阿拉伯语医疗口译，擅长国际患者中心和急诊陪同。',1),
('c09','Maria Santos','Maria Santos','female','Philippines',30,'["tl","en","ko"]',4.9,175,15000,19,'["Seoul Medical Center","National Medical Center"]','护理背景，熟悉英语及菲律宾语患者的检查和用药说明。',1),
('c10','Olga Petrova','Ольга Петрова','female','Russia',43,'["ru","en","ko"]',4.7,87,18000,38,'["Severance Hospital","Samsung Medical Center"]','俄语陪诊与住院流程协助，擅长材料整理和复诊安排。',1),
('c11','Carlos Ruiz','Carlos Ruiz','male','Spain',36,'["es","en","ko"]',4.8,104,16000,26,'["Seoul St. Marys Hospital","Konkuk University Hospital"]','西班牙语医疗翻译，熟悉骨科和运动医学流程。',1),
('c12','Emma Dubois','Emma Dubois','female','France',28,'["fr","en","ko"]',4.9,143,17500,21,'["Seoul National University Hospital","Severance Hospital"]','法语和英语陪诊，善于缓解初次就医患者的焦虑。',1),
('c13','Lukas Weber','Lukas Weber','male','Germany',39,'["de","en","ko"]',4.8,92,18500,34,'["Asan Medical Center","Seoul National University Hospital"]','德语医疗沟通，熟悉体检、心内科和长期随访。',1),
('c14','Ana Oliveira','Ana Oliveira','female','Brazil',33,'["pt-BR","es","en","ko"]',4.8,118,16000,25,'["Korea University Anam Hospital","National Medical Center"]','葡萄牙语与西班牙语患者陪诊，熟悉内科和妇科。',1),
('c15','Dewi Lestari','Dewi Lestari','female','Indonesia',26,'["id","ms","ko","en"]',4.7,101,13000,17,'["Seoul Medical Center","Konkuk University Hospital"]','印尼语陪诊，熟悉留学生保险和常见门诊流程。',1),
('c16','Pimchanok K.','พิมพ์ชนก','female','Thailand',37,'["th","ko","en"]',4.9,162,15500,29,'["Samsung Medical Center","Seoul St. Marys Hospital"]','泰语医疗翻译，熟悉健康检查和肿瘤中心就诊动线。',1),
('c17','Mert Kaya','Mert Kaya','male','Turkey',31,'["tr","en","ko"]',4.6,76,14500,32,'["Soonchunhyang University Hospital","Seoul Medical Center"]','土耳其语陪诊，擅长急诊沟通和药房取药协助。',1),
('c18','Giulia Rossi','Giulia Rossi','female','Italy',40,'["it","en","ko"]',4.8,110,17000,36,'["Severance Hospital","Asan Medical Center"]','意大利语医疗陪同，熟悉专科预约和检查结果说明。',1),
('c19','Oyun Erdene','Оюун-Эрдэнэ','female','Mongolia',35,'["mn","ko","ru"]',4.9,199,15000,23,'["Korea University Anam Hospital","Seoul National University Hospital"]','蒙古语医疗口译十年，熟悉住院、手术同意和出院流程。',1),
('c20','Aziz Karimov','Aziz Karimov','male','Uzbekistan',29,'["uz","ru","ko"]',4.7,84,13500,27,'["National Medical Center","Seoul Medical Center"]','乌兹别克语、俄语陪诊，熟悉工伤和门诊检查流程。',1),
('c21','Sara Khan','سارہ خان','female','Pakistan',34,'["ur","hi","en","ko"]',4.8,128,15500,31,'["Seoul St. Marys Hospital","Asan Medical Center"]','乌尔都语、印地语医疗沟通，尊重宗教和性别偏好。',1),
('c22','Nabila Rahman','নাবিলা রহমান','female','Bangladesh',27,'["bn","en","ko"]',4.7,79,12500,18,'["National Medical Center","Korea University Anam Hospital"]','孟加拉语陪诊，熟悉留学生常见内科与急诊流程。',1),
('c23','Arjun Shrestha','अर्जुन श्रेष्ठ','male','Nepal',42,'["ne","hi","en","ko"]',4.8,137,14500,33,'["Seoul Medical Center","Soonchunhyang University Hospital"]','尼泊尔语与印地语患者支持，熟悉工伤、骨科及康复流程。',1),
('c24','Thiri Aung','သီရိအောင်','female','Myanmar',30,'["my","en","ko"]',4.9,116,14000,20,'["Konkuk University Hospital","Seoul National University Hospital"]','缅甸语医疗口译，擅长体检、内科和女性健康陪诊。',1);
