const en = {
  askNaru: "Ask Naru about this document",
  askNaruHelp: "Unfamiliar terms or worrying results? Ask questions with this document attached. No need to wait for a translation.",
  title: "Let's read it together",
  subtitle: "Ask Naru about this document",
  welcome: "I can explain what this document says in everyday language. Ask about a term, what a result may mean, or what to check with your clinician. You can keep asking follow-up questions.",
  attached: "Reading this document",
  openDocument: "View document",
  detach: "Leave document chat",
  clinicalNote: "Naru explains the document; a diagnosis and treatment plan need a clinician's assessment. Check recognized text against the original.",
  questions: ["What does this document mean?", "Does it say I am sick?", "Is this serious?", "What should I do next?"],
  questionLabels: ["Explain simply", "Am I sick?", "Is it serious?", "Next steps"],
  placeholder: "Ask anything about this document…",
  send: "Send question",
  you: "You",
  thinking: "Naru is reading your document…",
  stillThinking: "Naru is still preparing your explanation…",
  elapsed: "{seconds}s",
  error: "Naru could not answer this time. Your question is still here. Please try again.",
  offline: "Check your connection and try again. Your question is still here.",
  unavailable: "This document is no longer available. Open your documents to choose another one.",
  expired: "Your session has expired. Sign in again to continue.",
  tooMany: "The service is busy. Wait a moment, then try your question again.",
  retry: "Try again",
  conversation: "Conversation about the attached document",
  memory: "This chat stays with this document while this page is open.",
};

type Copy = typeof en;
const zh: Copy = {
  askNaru: "拿这份文档问 Naru",
  askNaruHelp: "术语看不懂、担心检查结果？带上这份文档直接提问，不必等翻译完成。",
  title: "这份文档，我们一起看懂",
  subtitle: "和 Naru 聊聊这份文档",
  welcome: "我会用容易理解的话解释文档内容。某个词是什么意思、检查结果说明什么、接下来该问医生什么，都可以问我，也可以继续追问。",
  attached: "正在解读这份文档",
  openDocument: "查看文档",
  detach: "退出文档问答",
  clinicalNote: "Naru 帮你理解文档，是否患病及治疗方案需由医生结合实际情况判断。请先核对识别文字与原件。",
  questions: ["这份文档是什么意思？请用简单的话解释。", "这份文档是不是说我生病了？", "这份文档里的情况严重吗？", "我接下来应该怎么做？需要向医生确认什么？"],
  questionLabels: ["这是什么意思？", "我生病了吗？", "严重吗？", "接下来怎么做？"],
  placeholder: "关于这份文档，想问什么都可以…",
  send: "发送问题",
  you: "我",
  thinking: "Naru 正在阅读文档…",
  stillThinking: "Naru 还在整理解释，请稍候…",
  elapsed: "{seconds} 秒",
  error: "这次未能获得回答，你的问题仍保留在这里，请重试。",
  offline: "请检查网络连接后重试，你的问题仍保留在这里。",
  unavailable: "这份文档已不可用，请返回文档页面选择其他文档。",
  expired: "登录已过期，请重新登录后继续。",
  tooMany: "服务暂时繁忙，请稍候再试。",
  retry: "重新提问",
  conversation: "关于当前文档的对话",
  memory: "本次问答仅关联这份文档，关闭页面后不保留。",
};

const ko: Copy = {
  askNaru: "이 문서로 Naru에게 질문하기",
  askNaruHelp: "어려운 용어나 걱정되는 검사 결과가 있나요? 번역을 기다리지 않고 이 문서를 첨부해 질문할 수 있어요.",
  title: "이 문서, 함께 읽어봐요",
  subtitle: "Naru와 문서 이야기하기",
  welcome: "문서에 적힌 내용을 쉬운 말로 설명해 드릴게요. 용어의 뜻, 검사 결과의 의미, 의사에게 확인할 내용을 물어보세요. 이어서 궁금한 점을 더 질문해도 좋아요.",
  attached: "함께 읽고 있는 문서",
  openDocument: "문서 보기",
  detach: "문서 대화 나가기",
  clinicalNote: "Naru는 문서 이해를 도와드려요. 진단과 치료는 의사의 평가가 필요하며, 인식된 글자를 원본과 확인해 주세요.",
  questions: ["이 문서가 무슨 뜻인지 쉽게 설명해 주세요.", "이 문서에 제가 아프다고 나와 있나요?", "문서에 나온 상태가 심각한가요?", "다음에 무엇을 해야 하나요? 의사에게 무엇을 확인해야 하나요?"],
  questionLabels: ["무슨 뜻인가요?", "제가 아픈 건가요?", "심각한가요?", "다음은 어떻게?"],
  placeholder: "이 문서에 대해 무엇이든 물어보세요…",
  send: "질문 보내기",
  you: "나",
  thinking: "Naru가 문서를 읽고 있어요…",
  stillThinking: "Naru가 설명을 정리하고 있어요…",
  elapsed: "{seconds}초",
  error: "답변을 받지 못했어요. 질문은 그대로 남아 있으니 다시 시도해 주세요.",
  offline: "인터넷 연결을 확인하고 다시 시도해 주세요. 질문은 그대로 남아 있어요.",
  unavailable: "더 이상 사용할 수 없는 문서예요. 문서 페이지에서 다른 문서를 선택해 주세요.",
  expired: "로그인이 만료되었어요. 다시 로그인해 주세요.",
  tooMany: "지금은 요청이 많아요. 잠시 후 다시 시도해 주세요.",
  retry: "다시 질문하기",
  conversation: "첨부된 문서에 관한 대화",
  memory: "이 대화는 현재 문서에만 연결되며 페이지를 닫으면 사라져요.",
};

const ja: Copy = {
  askNaru: "この文書について Naru に質問",
  askNaruHelp: "難しい言葉や気になる検査結果はありますか？翻訳を待たずに、この文書を添えて質問できます。",
  title: "この文書、一緒に読みましょう",
  subtitle: "Naru と文書について話す",
  welcome: "文書の内容をわかりやすい言葉で説明します。用語の意味、検査結果の読み方、医師に確認したいことなどを聞いてください。続けて質問することもできます。",
  attached: "一緒に読んでいる文書",
  openDocument: "文書を見る",
  detach: "文書の会話を終了",
  clinicalNote: "Naru は文書の理解をお手伝いします。診断や治療には医師の評価が必要です。認識された文字を原本と確認してください。",
  questions: ["この文書の意味をわかりやすく説明してください。", "この文書は私が病気だと言っていますか？", "この文書の状態は深刻ですか？", "次に何をすればよいですか？医師に何を確認すべきですか？"],
  questionLabels: ["どういう意味？", "私は病気ですか？", "深刻ですか？", "次にすることは？"],
  placeholder: "この文書について何でも聞いてください…",
  send: "質問を送信",
  you: "自分",
  thinking: "Naru が文書を読んでいます…",
  stillThinking: "Naru が説明をまとめています…",
  elapsed: "{seconds}秒",
  error: "回答を取得できませんでした。質問は残っていますので、もう一度お試しください。",
  offline: "接続を確認して、もう一度お試しください。質問は残っています。",
  unavailable: "この文書は利用できなくなりました。文書ページで別の文書を選んでください。",
  expired: "ログインの有効期限が切れました。再度ログインしてください。",
  tooMany: "現在混み合っています。少し待ってからお試しください。",
  retry: "もう一度質問する",
  conversation: "添付文書についての会話",
  memory: "この会話はこの文書にのみ関連し、ページを閉じると消えます。",
};

export function documentConversationCopy(locale: string): Copy {
  if (locale.startsWith("zh")) return zh;
  if (locale.startsWith("ko")) return ko;
  if (locale.startsWith("ja")) return ja;
  return en;
}
