const en = {
  title: "Medical documents",
  navTitle: "Photo translation",
  subtitle: "Photograph prescriptions or test reports, or upload a photo or file. Review the recognized text, translate it, and ask Naru what it means and what to do next.",
  introduction: "Understand your medical documents",
  stepUpload: "Add a document",
  stepReview: "Review the text",
  stepTranslate: "Read the translation",
  takePhoto: "Take a photo",
  takePhotoHelp: "Use your camera",
  uploadPhoto: "Upload a photo",
  uploadPhotoHelp: "Choose from your photos",
  uploadFile: "Upload a file",
  uploadFileHelp: "PDF, TXT, JPG or PNG",
  formats: "PDF, TXT, JPG and PNG · Up to 10 MB per file · Up to 20,000 characters",
  pdfHelp: "PDF recognition reads selectable text only. Scanned pages and embedded images are not recognized. Check every page and upload page photos for image content.",
  uploadPrivacy: "Your document is uploaded to your account and sent to the AI service for text recognition and translation. You can delete it from your history.",
  demoTitle: "Sign in online to recognize your document",
  demoHelp: "You are signed in to an offline demo account. Sign in or create an online account to continue. Your selected photo or file will stay here.",
  connectAccount: "Connect online account",
  onlineLogin: "Sign in online",
  onlineRegister: "Create online account",
  onlineLoginFailed: "Check your account ID and password. If you only used the offline demo, create an online account.",
  onlineConnectionFailed: "Could not connect to the online service. Check your connection and try again; your selected file is still here.",
  invalidAccount: "Use an account ID of 2–48 letters, numbers, dots, hyphens or underscores.",
  sessionChanged: "Your sign-in changed in another window. Refresh the page and sign in again.",
  sourceLanguage: "Document language",
  targetLanguage: "Translate into",
  autoLanguage: "Detect automatically",
  selectedFile: "Selected document",
  removeFile: "Remove selected file",
  preview: "Selected medical document preview",
  upload: "Upload and extract text",
  uploading: "Uploading and recognizing text…",
  translating: "Translating your document…",
  loading: "Loading document…",
  deleting: "Deleting document…",
  downloading: "Preparing your download…",
  reviewTitle: "Review the recognized text",
  reviewHelp: "Check names, medication names, doses and numbers against the original. Correct any recognition errors before translating.",
  sourceText: "Original text",
  translate: "Translate document",
  translation: "Translation",
  translationReady: "Translation complete",
  translationEmpty: "Your translation will appear here after you review the text and select Translate document.",
  translationChanged: "The text or language has changed. Translate again to update the result.",
  clinicalNote: "AI translations may contain errors. Confirm medical decisions and medication instructions with your clinician.",
  emptyText: "No text was recognized. Upload clearer page photos, a PDF with selectable text, or a TXT file.",
  characterCount: "{count} / 20,000 characters",
  originalDownload: "Download original",
  translationDownload: "Download translation",
  historyTitle: "My documents",
  historyHelp: "Open a saved document to review or translate it again.",
  emptyHistory: "Your documents will appear here",
  emptyHistoryHelp: "Start by taking a photo or uploading a document above.",
  refresh: "Refresh",
  open: "Open",
  delete: "Delete",
  confirmDelete: "Delete this document and its translation? This cannot be undone.",
  cancel: "Cancel",
  saved: "Ready to translate",
  translated: "Translated",
  retry: "Try again",
  errorTitle: "Could not complete this step",
  cameraTitle: "Photograph your document",
  cameraHelp: "Place the whole page in the frame with good lighting and keep the camera steady.",
  cameraStarting: "Starting camera…",
  capture: "Capture photo",
  cameraFallback: "Use device camera / choose photo",
  cameraUnavailable: "The camera is unavailable. Allow camera access in your browser, or choose a photo below.",
  cameraDenied: "Camera access was denied. Enable camera permission in your browser, or choose an existing photo.",
  tooLarge: "The file is larger than 10 MB. Choose a smaller file.",
  invalidFile: "This file is empty or could not be read. Choose a valid document.",
  unsupportedFile: "Please choose a PDF, TXT, JPG or PNG file.",
  textTooLong: "The document exceeds 20,000 characters. Upload fewer pages or shorten the text.",
  languageError: "Choose a supported language and enter the document text before translating.",
  serviceUnavailable: "Document processing is not configured on the server. Please try again after the service is connected.",
  processingError: "The document could not be read. Try a clearer photo or an unlocked PDF, or upload a TXT file.",
  translationError: "Translation failed. Your original text is kept; please try again.",
  signInAgain: "Your session has expired. Please sign in again.",
  notFound: "This document is no longer available. Refresh your history.",
  documentChanged: "This document changed in another session. Open it from your history again before translating.",
  networkError: "The request could not finish. Check your connection and try again.",
  generalError: "Something went wrong. Please try again.",
};

export type MedicalDocumentCopy = typeof en;

const copies: Record<string, MedicalDocumentCopy> = {
  en,
  "zh-CN": {
    title: "医疗文档",
    navTitle: "拍照翻译",
    subtitle: "拍摄诊断书、处方或检查报告，也可以上传照片和文件。核对识别文字后翻译，或直接问 Naru：这是什么意思、严重吗、接下来怎么办。",
    introduction: "看懂您的医疗文档",
    stepUpload: "添加文档",
    stepReview: "核对文字",
    stepTranslate: "查看翻译",
    takePhoto: "拍照",
    takePhotoHelp: "使用相机拍摄",
    uploadPhoto: "上传照片",
    uploadPhotoHelp: "从相册选择照片",
    uploadFile: "上传文件",
    uploadFileHelp: "PDF、TXT、JPG 或 PNG",
    formats: "支持 PDF、TXT、JPG 和 PNG · 每个文件不超过 10 MB · 最多 20,000 字符",
    pdfHelp: "PDF 仅识别可选中的文字，不识别扫描页和内嵌图片。请逐页核对，图片内容请拍摄页面照片后上传。",
    uploadPrivacy: "文档将上传到您的账户，并发送至 AI 服务进行文字识别和翻译。您可以在历史记录中删除文档。",
    demoTitle: "登录在线账号后即可识别文档",
    demoHelp: "当前登录的是离线演示账号。请登录或注册在线账号继续使用，已选择的照片或文件会保留。",
    connectAccount: "连接在线账号",
    onlineLogin: "登录在线账号",
    onlineRegister: "注册在线账号",
    onlineLoginFailed: "请检查账号和密码。如果之前仅使用离线演示，请先注册在线账号。",
    onlineConnectionFailed: "暂时无法连接在线服务，请检查网络后重试。已选择的文件仍会保留。",
    invalidAccount: "账号需要 2–48 个字符，可使用字母、数字、点、连字符或下划线。",
    sessionChanged: "登录状态已在其他窗口中改变，请刷新页面后重新登录。",
    sourceLanguage: "文档语言",
    targetLanguage: "翻译为",
    autoLanguage: "自动识别",
    selectedFile: "已选择的文档",
    removeFile: "移除所选文件",
    preview: "所选医疗文档预览",
    upload: "上传并识别文字",
    uploading: "正在上传并识别文字…",
    translating: "正在翻译文档…",
    loading: "正在加载文档…",
    deleting: "正在删除文档…",
    downloading: "正在准备下载…",
    reviewTitle: "核对识别文字",
    reviewHelp: "请对照原文核对姓名、药品名称、剂量及数字，修正识别错误后再翻译。",
    sourceText: "原文",
    translate: "翻译文档",
    translation: "译文",
    translationReady: "翻译完成",
    translationEmpty: "核对文字后点击“翻译文档”，译文将在这里显示。",
    translationChanged: "原文或语言已更改，请重新翻译以更新结果。",
    clinicalNote: "AI 翻译可能存在错误。医疗决定和用药说明请与医护人员确认。",
    emptyText: "未识别到文字，请上传更清晰的页面照片、文字可选中的 PDF 或 TXT 文件。",
    characterCount: "{count} / 20,000 字符",
    originalDownload: "下载原文件",
    translationDownload: "下载译文",
    historyTitle: "我的文档",
    historyHelp: "打开已保存的文档，继续核对或重新翻译。",
    emptyHistory: "您的文档将在这里显示",
    emptyHistoryHelp: "从上方拍照或上传文档开始。",
    refresh: "刷新",
    open: "打开",
    delete: "删除",
    confirmDelete: "删除此文档及译文？此操作无法撤销。",
    cancel: "取消",
    saved: "待翻译",
    translated: "已翻译",
    retry: "重试",
    errorTitle: "未能完成此步骤",
    cameraTitle: "拍摄医疗文档",
    cameraHelp: "请将整页放入画面，保持光线充足并握稳相机。",
    cameraStarting: "正在启动相机…",
    capture: "拍摄照片",
    cameraFallback: "使用设备相机 / 选择照片",
    cameraUnavailable: "相机不可用。请允许浏览器使用相机，或从下方选择照片。",
    cameraDenied: "相机权限已被拒绝。请在浏览器中开启相机权限，或选择现有照片。",
    tooLarge: "文件超过 10 MB，请选择较小的文件。",
    invalidFile: "文件为空或无法读取，请选择有效文档。",
    unsupportedFile: "请选择 PDF、TXT、JPG 或 PNG 文件。",
    textTooLong: "文档超过 20,000 字符，请减少上传页数或缩短文字。",
    languageError: "请选择支持的语言并输入文档原文后再翻译。",
    serviceUnavailable: "服务器尚未配置文档处理服务，请在服务连接后重试。",
    processingError: "无法读取文档。请尝试更清晰的照片、未加密的 PDF 或 TXT 文件。",
    translationError: "翻译失败，原文已保留，请重试。",
    signInAgain: "登录已过期，请重新登录。",
    notFound: "此文档已不可用，请刷新历史记录。",
    documentChanged: "此文档已在其他会话中更改，请从历史记录重新打开后再翻译。",
    networkError: "请求未能完成，请检查网络连接并重试。",
    generalError: "出现错误，请重试。",
  },
  ko: {
    title: "의료 문서",
    navTitle: "사진 번역",
    subtitle: "진단서, 처방전, 검사 결과를 촬영하거나 사진과 파일을 업로드하세요. 인식된 내용을 확인한 뒤 번역하거나 Naru에게 의미와 다음에 할 일을 물어보세요.",
    introduction: "내 의료 문서를 이해하세요",
    stepUpload: "문서 추가",
    stepReview: "내용 확인",
    stepTranslate: "번역 보기",
    takePhoto: "사진 촬영",
    takePhotoHelp: "카메라로 촬영하기",
    uploadPhoto: "사진 업로드",
    uploadPhotoHelp: "앨범에서 사진 선택",
    uploadFile: "파일 업로드",
    uploadFileHelp: "PDF, TXT, JPG 또는 PNG",
    formats: "PDF, TXT, JPG, PNG 지원 · 파일당 최대 10 MB · 최대 20,000자",
    pdfHelp: "PDF는 선택 가능한 텍스트만 인식합니다. 스캔한 페이지와 삽입된 이미지는 인식하지 못하므로 모든 페이지를 확인하고 이미지 내용은 페이지 사진으로 업로드하세요.",
    uploadPrivacy: "문서는 계정에 업로드되고 문자 인식과 번역을 위해 AI 서비스로 전송됩니다. 기록에서 문서를 삭제할 수 있습니다.",
    demoTitle: "온라인 계정에 로그인하면 문서를 인식할 수 있어요",
    demoHelp: "현재 오프라인 데모 계정으로 로그인되어 있습니다. 온라인 계정에 로그인하거나 가입해 주세요. 선택한 사진이나 파일은 그대로 유지됩니다.",
    connectAccount: "온라인 계정 연결",
    onlineLogin: "온라인 계정 로그인",
    onlineRegister: "온라인 계정 만들기",
    onlineLoginFailed: "아이디와 비밀번호를 확인해 주세요. 오프라인 데모만 사용했다면 온라인 계정을 만들어 주세요.",
    onlineConnectionFailed: "온라인 서비스에 연결할 수 없습니다. 인터넷 연결을 확인하고 다시 시도해 주세요. 선택한 파일은 유지됩니다.",
    invalidAccount: "아이디는 문자, 숫자, 점, 하이픈 또는 밑줄을 사용해 2–48자로 입력해 주세요.",
    sessionChanged: "다른 창에서 로그인 상태가 변경되었습니다. 페이지를 새로고침하고 다시 로그인해 주세요.",
    sourceLanguage: "문서 언어",
    targetLanguage: "번역할 언어",
    autoLanguage: "자동 감지",
    selectedFile: "선택한 문서",
    removeFile: "선택한 파일 제거",
    preview: "선택한 의료 문서 미리보기",
    upload: "업로드 및 문자 인식",
    uploading: "문서를 업로드하고 글자를 인식하고 있어요…",
    translating: "문서를 번역하고 있어요…",
    loading: "문서를 불러오고 있어요…",
    deleting: "문서를 삭제하고 있어요…",
    downloading: "다운로드를 준비하고 있어요…",
    reviewTitle: "인식된 내용을 확인하세요",
    reviewHelp: "이름, 약 이름, 용량, 숫자를 원본과 대조하고 인식 오류를 수정한 뒤 번역하세요.",
    sourceText: "원문",
    translate: "문서 번역",
    translation: "번역문",
    translationReady: "번역 완료",
    translationEmpty: "내용을 확인한 뒤 ‘문서 번역’을 누르면 번역문이 여기에 표시됩니다.",
    translationChanged: "원문이나 언어가 바뀌었습니다. 다시 번역해 결과를 업데이트하세요.",
    clinicalNote: "AI 번역에 오류가 있을 수 있습니다. 의료 결정과 복약 안내는 의료진에게 확인하세요.",
    emptyText: "글자를 인식하지 못했습니다. 더 선명한 페이지 사진, 텍스트를 선택할 수 있는 PDF 또는 TXT 파일을 업로드하세요.",
    characterCount: "{count} / 20,000자",
    originalDownload: "원본 다운로드",
    translationDownload: "번역문 다운로드",
    historyTitle: "내 문서",
    historyHelp: "저장된 문서를 열어 내용을 확인하거나 다시 번역할 수 있습니다.",
    emptyHistory: "문서가 여기에 표시돼요",
    emptyHistoryHelp: "위에서 사진을 촬영하거나 문서를 업로드해 시작하세요.",
    refresh: "새로고침",
    open: "열기",
    delete: "삭제",
    confirmDelete: "이 문서와 번역문을 삭제할까요? 삭제 후에는 복구할 수 없습니다.",
    cancel: "취소",
    saved: "번역 대기",
    translated: "번역 완료",
    retry: "다시 시도",
    errorTitle: "이 단계를 완료하지 못했어요",
    cameraTitle: "의료 문서 촬영",
    cameraHelp: "페이지 전체가 화면에 나오도록 맞추고, 밝은 곳에서 흔들리지 않게 촬영하세요.",
    cameraStarting: "카메라를 시작하고 있어요…",
    capture: "사진 찍기",
    cameraFallback: "기기 카메라 / 사진 선택",
    cameraUnavailable: "카메라를 사용할 수 없습니다. 브라우저의 카메라 권한을 허용하거나 아래에서 사진을 선택하세요.",
    cameraDenied: "카메라 접근이 거부되었습니다. 브라우저에서 카메라 권한을 허용하거나 기존 사진을 선택하세요.",
    tooLarge: "파일이 10 MB를 초과합니다. 더 작은 파일을 선택하세요.",
    invalidFile: "파일이 비어 있거나 읽을 수 없습니다. 유효한 문서를 선택하세요.",
    unsupportedFile: "PDF, TXT, JPG 또는 PNG 파일을 선택하세요.",
    textTooLong: "문서가 20,000자를 초과합니다. 페이지 수를 줄이거나 내용을 줄여주세요.",
    languageError: "지원되는 언어를 선택하고 문서 원문을 입력한 뒤 번역하세요.",
    serviceUnavailable: "서버에 문서 처리 서비스가 설정되어 있지 않습니다. 서비스 연결 후 다시 시도하세요.",
    processingError: "문서를 읽을 수 없습니다. 더 선명한 사진, 암호가 없는 PDF 또는 TXT 파일을 업로드하세요.",
    translationError: "번역에 실패했습니다. 원문은 유지되니 다시 시도하세요.",
    signInAgain: "로그인이 만료되었습니다. 다시 로그인하세요.",
    notFound: "이 문서를 찾을 수 없습니다. 기록을 새로고침하세요.",
    documentChanged: "다른 세션에서 문서가 변경되었습니다. 기록에서 다시 열고 번역하세요.",
    networkError: "요청을 완료하지 못했습니다. 인터넷 연결을 확인하고 다시 시도하세요.",
    generalError: "오류가 발생했습니다. 다시 시도하세요.",
  },
  ja: {
    title: "医療文書",
    navTitle: "写真翻訳",
    subtitle: "診断書や処方箋、検査結果を撮影するか、写真やファイルをアップロードしてください。認識された文字を確認して翻訳し、意味や次にすることをNaruに質問できます。",
    introduction: "医療文書の内容を理解しましょう",
    stepUpload: "文書を追加",
    stepReview: "内容を確認",
    stepTranslate: "翻訳を読む",
    takePhoto: "写真を撮る",
    takePhotoHelp: "カメラで撮影",
    uploadPhoto: "写真をアップロード",
    uploadPhotoHelp: "アルバムから選択",
    uploadFile: "ファイルをアップロード",
    uploadFileHelp: "PDF、TXT、JPG または PNG",
    formats: "PDF、TXT、JPG、PNG 対応 · 1ファイル最大 10 MB · 最大 20,000 文字",
    pdfHelp: "PDF は選択可能な文字のみ認識します。スキャンしたページや埋め込み画像は認識されません。全ページを確認し、画像の内容はページを撮影してアップロードしてください。",
    uploadPrivacy: "文書はアカウントにアップロードされ、文字認識と翻訳のため AI サービスに送信されます。履歴から削除できます。",
    demoTitle: "オンラインアカウントにログインして文字を認識",
    demoHelp: "現在はオフラインのデモアカウントです。オンラインアカウントにログインするか、新規登録してください。選択した写真やファイルは保持されます。",
    connectAccount: "オンラインアカウントに接続",
    onlineLogin: "オンラインアカウントにログイン",
    onlineRegister: "オンラインアカウントを登録",
    onlineLoginFailed: "アカウントIDとパスワードを確認してください。オフラインデモのみ利用した場合は、オンラインアカウントを登録してください。",
    onlineConnectionFailed: "オンラインサービスに接続できません。接続を確認して再試行してください。選択したファイルは保持されます。",
    invalidAccount: "IDは文字、数字、ピリオド、ハイフン、アンダースコアを使い2～48文字で入力してください。",
    sessionChanged: "別のウィンドウでログイン状態が変わりました。ページを更新して再度ログインしてください。",
    sourceLanguage: "文書の言語",
    targetLanguage: "翻訳先の言語",
    autoLanguage: "自動検出",
    selectedFile: "選択した文書",
    removeFile: "選択したファイルを削除",
    preview: "選択した医療文書のプレビュー",
    upload: "アップロードして文字を認識",
    uploading: "アップロードして文字を認識しています…",
    translating: "文書を翻訳しています…",
    loading: "文書を読み込んでいます…",
    deleting: "文書を削除しています…",
    downloading: "ダウンロードを準備しています…",
    reviewTitle: "認識された内容を確認",
    reviewHelp: "氏名、薬の名前、用量、数値を原本と照合し、認識の誤りを修正してから翻訳してください。",
    sourceText: "原文",
    translate: "文書を翻訳",
    translation: "翻訳文",
    translationReady: "翻訳完了",
    translationEmpty: "内容を確認して「文書を翻訳」を押すと、ここに翻訳文が表示されます。",
    translationChanged: "原文または言語が変更されました。再度翻訳して結果を更新してください。",
    clinicalNote: "AI 翻訳には誤りが含まれる場合があります。医療上の判断や服薬の説明は医療従事者に確認してください。",
    emptyText: "文字が認識されませんでした。鮮明なページ写真、文字を選択できる PDF、または TXT ファイルをアップロードしてください。",
    characterCount: "{count} / 20,000 文字",
    originalDownload: "原本をダウンロード",
    translationDownload: "翻訳文をダウンロード",
    historyTitle: "マイ文書",
    historyHelp: "保存した文書を開き、内容の確認や再翻訳ができます。",
    emptyHistory: "文書がここに表示されます",
    emptyHistoryHelp: "上から写真を撮影するか、文書をアップロードして始めましょう。",
    refresh: "更新",
    open: "開く",
    delete: "削除",
    confirmDelete: "この文書と翻訳文を削除しますか？この操作は取り消せません。",
    cancel: "キャンセル",
    saved: "翻訳待ち",
    translated: "翻訳済み",
    retry: "再試行",
    errorTitle: "この手順を完了できませんでした",
    cameraTitle: "医療文書を撮影",
    cameraHelp: "ページ全体が画面に収まるようにして、明るい場所でカメラを固定して撮影してください。",
    cameraStarting: "カメラを起動しています…",
    capture: "撮影する",
    cameraFallback: "端末のカメラ / 写真を選択",
    cameraUnavailable: "カメラを利用できません。ブラウザでカメラを許可するか、下から写真を選択してください。",
    cameraDenied: "カメラへのアクセスが拒否されました。ブラウザで許可するか、既存の写真を選択してください。",
    tooLarge: "ファイルが 10 MB を超えています。小さいファイルを選択してください。",
    invalidFile: "ファイルが空か読み取れません。有効な文書を選択してください。",
    unsupportedFile: "PDF、TXT、JPG または PNG ファイルを選択してください。",
    textTooLong: "文書が 20,000 文字を超えています。ページ数または文字数を減らしてください。",
    languageError: "対応する言語を選択し、原文を入力してから翻訳してください。",
    serviceUnavailable: "サーバーに文書処理サービスが設定されていません。サービス接続後に再試行してください。",
    processingError: "文書を読み取れません。鮮明な写真、暗号化されていない PDF、または TXT ファイルをお試しください。",
    translationError: "翻訳に失敗しました。原文は保持されています。再試行してください。",
    signInAgain: "セッションが切れました。再度ログインしてください。",
    notFound: "この文書は利用できなくなりました。履歴を更新してください。",
    documentChanged: "別のセッションで文書が変更されました。履歴から開き直して翻訳してください。",
    networkError: "リクエストを完了できませんでした。接続を確認して再試行してください。",
    generalError: "エラーが発生しました。再試行してください。",
  },
};

export function medicalDocumentCopy(locale: string): MedicalDocumentCopy {
  return copies[locale] || copies.en;
}
